colors:
  tan100: "#e0d4b5"
  tan50: "#ece4d1"
  tan25: "#f7f4ec"
  grey100: "#5B6771"
  grey50: "#b7bfc5"
  grey25: "#d8dce0"
  red100: "#d83632"
  red50: "#eb9795"
  red25: "#fbe8e8"
  yellow125: "#FFF700"
  yellow100: "#F1B51C"
  yellow50: "#f8d98b"
  yellow25: "#fbebc2"
  green100: "#046B5C"
  teal100 : "#189394"
  purple100: "#360B7F"
  black100: "000000"
  white100: "#FFFFFF"
  accent: "#046B5C"
formatting:
  digits: 2
